### ISSUE TITLE
Implement GitHub stars alerts

### ISSUE THREAD

**Issue by bdougie** [mutualfun/beybot#3]
@sgrove shared this on stream.

https://www.onegraph.com/graphiql?shortenedId=KXGZKK

## Plan

1. Set up an onegraph app using a subscription to the open sauced repo
2. Embed the app into the beybot HTML 

(probably introduce beybot to a framework to make).

**Comment by bdougie** [comment]
Discover today that the subscription has been deprecated. 

I am considering just approaching this with a webhook to trigger a css animation.

**Comment by sgrove** [comment]
What subscription specifically?

**Comment by bdougie** [comment]
I was looking to leverage this:

```
subscription OnStarEvent {
  github {
    starEvent(input: { repoOwner: "", repoName: "" }) {
      sender {
        login
      }
    }
  }
}

```

Going to create a Twitch alert when a repo is starred for the beybot. I am leaning towards leveraging a webhook that triggers a Netlify function now.

**Comment by sgrove** [comment]
So GraphQL lets you specify fields as "deprecated", and tooling will kind of hide those fields by default.

In this case, we mark it as deprecated with the reason `Beta: this field is still in beta while we work out the kinks.` - so it's not going away, it's just that while we work on the implementation/polish things up, we want tooling to not show it too prominently to most people.

I wish GraphQL could let you mark a field as "beta" rather than "deprecated", heh.

But, long story short, feel free to use it, it's not going away!

**Comment by sgrove** [comment]
Also, if you'd like to pair on this, it'd be a lot of fun, and we could
have it done in ~20 minutes I suspect (famous last words!)

**Comment by bdougie** [comment]
I have moved this to https://github.com/open-sauced/slaybot. 

1. Because I have content that relies on that that the beybot live on GitHub Pages for work reasons. 
2. I will start leveraging the slaybot moving forward as the backbone of the bdougie.live streams and have any dependencies on public blog posts.
